# Generated by Django 4.2.7 on 2023-11-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aplicacao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                ("actor_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
