# Generated by Django 4.2.7 on 2023-11-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aplicacao", "0002_actor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
